language: node_js

before_install:
  - '[[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install nvm || echo skip brew'

script:
  - node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --compilers coffee:coffee-script/register
  - cat coverage/lcov.info | node_modules/.bin/coveralls
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
os:
  - linux
  - osx

notifications:
  slack:
    secure: XeHEzoQDiH0PaXwATrCchAN3sNpqYb/IHLeFr5BwwNo9+R4cwvo5FqPOY/qWNo6BwmJ1lcAG7gsipfz/MQNEjKpFQLeQ6n/igBQuj19hC8ZFs/GL8qHjfwL4ZbWntEEcDsJJRFW73z5nQif2t135D/DWoUuoXg2ZZNkA8F3Nwg8bNw/wIuPNI4K3JjZvm3zDm/Ck6X5SkKU1unliXMl7cCjE0MxibDTcEyVEaFo6ir8DCy+qwcTdydaVThiaR0tItA+Cx+1Z5yeT1lxTzheEVPeXmCC/Xx3ZUNsM7mq+QW32BwSbeMra5Sc7bf5yolUEF8NI+Kt2mZ/eIsERLt7tms4LuEUqnekKWT6bccgvdUlA/DdgvaCz5fdcWg9xh6U3WM9vOHz7DVcV76Ib06XNaj8FZ3HAgem1XBYJmPKT5VbnWTQLgBesWjXwtWMbiAm44VtzqAaSBpEwGLZh8+nAWkIItTGdY1b9bAETaVGR3RspAhLOAVvanpITK7KOF1KYkZQ/9/G9SrVbEZD9FFT8SG7g8VoNtPtERJIS/lPeI4Yunj1kj8BcZmZxEtGOp+795r6b7oi22dXpQlQnzJOJO+WnWS4s6ABqLhNlQVK6jEvyUvVKAxz+jaYG0i+X/9PcYOnWKwVK9P+A76/B3CPBc+grANiXP9Wpk3qMQtUh8d0=
